name: Output Information
on: workflow_dispatch # Triggers manually
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: echo "${{ toJson(github) }}"
      